<?php

/**
 * PluginsfGuardUserCultureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardUserCultureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginsfGuardUserCultureTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardUserCulture');
    }
}